name: art_pen
version: 2.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: DArt Pen is a Logo language. dartling is a domain model framework.
homepage: http://ondart.me/
documentation: http://goo.gl/OvQWwN
dependencies:
  browser: any
  dartling: any
  dartling_default_app: any
